name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet
        run: |
          pip install flet==0.84.0
          pip install "flet[all]"

      - name: Build APK
        run: |
          # 1. Initialize the project structure so we can modify it
          flet create tmp_app
          cp main.py tmp_app/
          cp icon.png tmp_app/
          
          # 2. Run the build from inside that folder
          # We use --project here because it's the only flag 0.84.0 consistently likes
          cd tmp_app
          flet build apk --project "Age Calculator" --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AgeCalculator-APK
          path: tmp_app/build/apk/**/*.apk
          
