name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Flet and Dependencies
        run: |
          pip install flet==0.84.0
          # We need 'flet[all]' to access the build CLI tools
          pip install "flet[all]" 

      - name: Build APK
        run: |
          flet build apk \
            --name "Age Calculator" \
            --icon icon.png \
            --splash-image icon.png \
            --splash-color "#1A1C1E"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AgeCalculator-APK
          # Flet builds usually output to the 'build/apk' directory
          path: build/apk/*.apk
          
